version: '3.8'

services:
  tts-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount outputs directory for persistence
      - ./outputs:/app/outputs
      # Mount .env file for configuration
      - ./.env:/app/.env:ro
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
