# -*- coding: utf-8 -*-
"""Копия блокнота "xTTS.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YwVOYFKpprI-J5lrdLv3l--yHxdSN59f

# 🗣️ xTTS Google Colab

## 📄 Description  
This Colab notebook uses xTTS V2 to generate speech from text. It provides natural text-to-speech and voice-cloning with short reference audio.  

**Languages supported**: English (en), Spanish (es), French (fr), German (de), Italian (it), Portuguese (pt), Polish (pl), Turkish (tr), Russian (ru), Dutch (nl), Czech (cs), Arabic (ar), Chinese (zh-cn), Japanese (ja), Hungarian (hu), Korean (ko) Hindi (hi)  
**Capabilities**: Text-to-speech, Predefined Voices, Multi-lingual, Voice Cloning

---

## 🔗 Resources

- **GitHub Repository:** https://github.com/coqui-ai/TTS, https://github.com/idiap/coqui-ai-TTS (Original Coqui TTS is no longer maintained as Coqui shut down in 2023.)  
- **Model Availability:** https://huggingface.co/coqui/XTTS-v2

---

## 🎙️ Explore More TTS Models  
Want to try out additional TTS models? Check out the curated collection here:  
👉 [awesome-TTS-Colab](https://github.com/Troyanovsky/awesome-TTS-Colab)

## Text-to-speech
"""

!pip install coqui-tts[languages]
# Original TTS is no longer maintained as Coqui TTS shut down in 2023

TEXT = "This is text to speech generated by XTTS" # Change to the text you want to generate

TEXT = "щас весь американский ютуб на этом голосе))" # Change to the text you want to generate

import torch
from TTS.api import TTS
from IPython.display import Audio

device = "cuda" if torch.cuda.is_available() else "cpu"

tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)

print(tts.speakers)

# Text to speech to a file
tts.tts_to_file(text=TEXT, language="ru", file_path="output.wav", speaker="Daisy Studious")

Audio("output.wav")

"""## Voice Cloning with Reference Audio"""

TEXT = "щас весь американский ютуб на этом голосе))" # Change to the text you want to generate

# Run everything in the previous section, except the last cell.
# Run the following instead

from google.colab import files
import os

print("Please upload your reference audio file.")
uploaded = files.upload()

# Get the uploaded file name
reference_audio = list(uploaded.keys())[0]

# Rename the uploaded file to reference_audio.wav
os.rename(reference_audio, "reference_audio.wav")
print("File uploaded and renamed to reference_audio.wav")



# Text to speech to a file, using a reference input audio
tts.tts_to_file(text=TEXT,
                language="ru",
                file_path="output.wav",
                speaker_wav="reference_audio.wav")

Audio("output.wav")